# Generated by Django 3.2.18 on 2023-03-01 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Names',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'test_table',
                'managed': False,
            },
        ),
    ]
